=== cexiolabs/cexiopay.schemas/api/v3/gateway/gateway_order_confirm_response.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://schemas.cexpay.io/api/v3/gateway/gateway_order_create.json",
	"title": "Gateway order confirmation response data transfer object",
	"description": "Gateway order confirmation data transfer object is used as response body for confirmation Gateway order.",
	"type": "object",
	"properties": {
		"id": {
			"$ref": "https://schemas.cexpay.io/api/v3/gateway/identifier-account.json",
			"title": "An unique identifier of an gateway order."
		},
		"createdAt": {
			"ref": "https://schemas.cexpay.io/api/v3/primitives.json#/definitions/date",
			"title": "Account creation date"
		},
		"updatedAt": {
			"ref": "https://schemas.cexpay.io/api/v3/primitives.json#/definitions/date",
			"title": "Account creation date"
		},
		"confirmedAt": {
			"ref": "https://schemas.cexpay.io/api/v3/primitives.json#/definitions/date",
			"title": "Account creation date"
		},
		"tag": {
			"type": [
				"string",
				"null"
			],
			"maxLength": 1024,
			"title": "Any client's tag",
			"description": "Optional. Clients may save here any related data."
		},
		"description": null,
		"okRedirect": null,
		"failRedirect": null,
		"emailSpecified": true,
		"instrument": {
			"type": "string",
			"const": "CRYPTO_SELL"
		},
		"model": {
			"type": "string",
			"const": "DEFAULT"
		},
		"state": {
			"enum": [
				"AWAIT_DEPOSIT",
				"COMPLETED"
			],
			"description": "Current order state."
		},
		"rejectionReason": null,
		"paidStatus": "NONE",
		"expiredAt": {
			"ref": "https://schemas.cexpay.io/api/v3/primitives.json#/definitions/date",
			"title": "Account creation date"
		},
		"rate": {
			"symbol": "ETH/USD",
			"rate": {
				"$ref": "https://schemas.cexpay.io/api/v3/primitives.json#definitions/financialPositive",
				"title": "Amount",
				"description": "Gateway order amount."
			}
		},
		"from": {
			"accountId": {
				"$ref": "https://schemas.cexpay.io/api/v3/account/identifier-account.json",
				"title": "Account unique identifier."
			},
			"currency": {
				"$ref": "https://schemas.cexpay.io/api/v3/currency.json#/definitions/currencyCrypto",
				"title": "Currency code (like 'BTC', 'ETH', etc)."
			},
			"amount": {
				"$ref": "https://schemas.cexpay.io/api/v3/primitives.json#definitions/financialPositive",
				"title": "Amount",
				"description": "Gateway order amount."
			}
		},
		"to": {
			"accountId": {
				"$ref": "https://schemas.cexpay.io/api/v3/account/identifier-account.json",
				"title": "Account unique identifier."
			},
			"currency": {
				"$ref": "https://schemas.cexpay.io/api/v3/currency.json#/definitions/currencyFiat",
				"title": "Currency code (like 'USD', 'EUR', etc)."
			},
			"amount": {
				"$ref": "https://schemas.cexpay.io/api/v3/primitives.json#definitions/financialPositive",
				"title": "Amount",
				"description": "Gateway order amount."
			}
		},
		"deposit": {
			"address": {
				"type": "string",
				"minLength": 1,
				"maxLength": 256,
				"title": "Incoming crypto address."
			},
			"uri": "ethereum:0x01472ba7396d1cc22e7e0cbe735ad2dbec499943?value=1.54845886",
			"amount": {
				"$ref": "https://schemas.cexpay.io/api/v3/primitives.json#definitions/financialPositive",
				"title": "Amount",
				"description": "Gateway order amount."
			},
			"underpayment": {
				"$ref": "https://schemas.cexpay.io/api/v3/primitives.json#definitions/financialPositive",
				"title": "Amount",
				"description": "Gateway order amount."
			}
		},
		"depositAcceptConfirmations": {
			"type": "integer",
			"minimum": 0,
			"description": "Number of blockchain confirmations"
		}
	},
	"required": [
		"instrument",
		"model",
		"to"
	]
}

=== cexiolabs/cexiopay.schemas/gateway/v2/gate.get-order.SAMPLE-2.json
{
	"id": "7ae366f4-c193-46cf-a6c3-ba6f4ba0c93e",
	"createdAt": "2021-09-15T13:20:36.916924+03:00",
	"updatedAt": "2021-09-15T13:20:36.916926+03:00",
	"confirmedAt": "2021-09-15T13:20:36.916927+03:00",
	"tag": "Some tag for invoice 7ae366f4-c193-46cf-a6c3-ba6f4ba0c93e",
	"description": "Some description for invoice 7ae366f4-c193-46cf-a6c3-ba6f4ba0c93e",
	"okRedirect": "https://example.com/order/success",
	"failRedirect": "https://example.com/order/failure",
	"emailSpecified": true,
	"expiredAt": "2021-09-15T13:40:36.916929+03:00",
	"rate": {
		"symbol": "BTC/USD",
		"rate": "49833.0807"
	},
	"instrument": "CRYPTO_SELL",
	"model": "DEFAULT",
	"state": "AWAIT_DEPOSIT",
	"rejectionReason": null,
	"paidStatus": "NONE",
	"from": {
		"currency": "BTC",
		"amount": "0.00016054"
	},
	"to": {
		"currency": "USD",
		"amount": "8"
	},
	"deposit": {
		"address": "2MwwYWnpmuiAgysbUBkqM7HLjshSy3X1TTN",
		"uri": "bitcoin:2MwwYWnpmuiAgysbUBkqM7HLjshSy3X1TTN?amount=0.00016054&label=32af53b0-01bb-43b0-a5ef-870847919d56",
		"amount": "0",
		"underpayment": "0.00016054"
	},
	"depositAcceptConfirmations": 5
}
