=== cexiolabs/cexiopay.schemas/api/v3/order/return.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://schemas.pay-cex.io/api/v3/order/return.json",
	"title": "Return creation request data transfer object",
	"description": "Return-token data transfer object is used as request body for Register Return. See https://developers.pay-cex.io/api/#register-return",
	"type": "object",
	"properties": {
		"returnId": {
			"$ref": "https://schemas.pay-cex.io/api/v3/order/return-identifier.json",
			"title": "Return operation unique identifier."
		},
		"returnClientId": {
			"type": [
				"string",
				"null"
			],
			"maxLength": 128,
			"title": "Optional. Client-side return identifier.",
			"description": "It may used to prevent duplicate returns."
		},
		"returnClientTag": {
			"type": [
				"string",
				"null"
			],
			"maxLength": 1024,
			"title": "Any client's tag",
			"description": "API clients may save here any related data."
		},
		"createdAt": {
			"ref": "https://schemas.pay-cex.io/api/v3/primitives.json#/definitions/date",
			"title": "Return creation date"
		},
		"status": {
			"title": "Status of the return operation",
			"description": "See https://developers.pay-cex.io/api/#status-enum",
			"enum": [
				"NEW",
				"CANCELLED",
				"APPROVE_AWAITING",
				"APPROVE_REJECTED",
				"WITHDRAWAL_PENDING",
				"WITHDRAWAL_COMPLETED",
				"WITHDRAWAL_REJECTED"
			]
		},
		"risks": {
			"title": "Set of risk flags",
			"description": "These flags are used as warning to prevent potential losses by human-factor actions. Like enter wrong address, etc...",
			"type": "array",
			"items": {
				"type": "string"
			}
		},
		"userFeeFactor": {
			"$ref": "https://schemas.pay-cex.io/api/v3/primitives.json#definitions/zeroOneFactor",
			"title": "User's fee (factor)",
			"description": "User's fee (factor) is a stringified decimal value in range [0.0..1.0]. The value shown - how many percent of fee will be charged for an user. Example: value = 0.0 - merchant will pay all fee; value = 0.425 - user will pay 42.5% of fee and merchant will pay 57.5% of fee; value = 1.0 - user will pay all fee."
		},
		"currency": {
			"$ref": "https://schemas.pay-cex.io/api/v3/currency.json#/definitions/currencyCrypto",
			"title": "Currency code of the account (like 'BTC', 'ETH', etc)."
		},
		"returnAddress": {
			"type": "string",
			"minLength": 1,
			"maxLength": 256,
			"title": "User's return address",
			"description": "User's return address is a target address for return operation."
		}
	},
	"required": [
		"returnId",
		"returnClientId",
		"returnClientTag",
		"createdAt",
		"status",
		"risks",
		"userFeeFactor",
		"currency",
		"returnAddress"
	]
}

=== cexiolabs/cexiopay.schemas/api/v3/order/return.SAMPLE-3.json
{
	"$schema": "https://schemas.pay-cex.io/api/v3/order/return.json",
	"returnId": "CPR-a87264592a6b4304be70882b7f24cd1e",
	"returnClientId": null,
	"returnClientTag": null,
	"createdAt": "2021-05-24T18:22:27.024159Z",
	"status": "WITHDRAWAL_PENDING",
	"risks": [],
	"userFeeFactor": "0.425",
	"currency": "BTC",
	"returnAddress": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
}
