=== cexiolabs/cexiopay.schemas/api/v3/invoice/invoice.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://schemas.pay-cex.io/api/v3/invoice/invoice.json",
	"title": "Base Invoice Object",
	"type": "object",
	"properties": {
		"currency": {
			"type": "string"
		},
		"amount": {
			"$ref": "https://schemas.pay-cex.io/api/v3/primitives.json#definitions/financialPositive",
			"title": "Total Due of the invoice"
		},
		"notes": {
			"type": "string",
			"title": "Notes",
			"description": "Notes"
		},
		"items": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"description": {
						"type": "string",
						"title": "Description",
						"description": "Description of invoice item."
					},
					"quantity": {
						"$ref": "https://schemas.pay-cex.io/api/v3/primitives.json#definitions/financialPositive",
						"title": "Quantity",
						"description": "Quantity of invoice item."
					},
					"unitPrice": {
						"$ref": "https://schemas.pay-cex.io/api/v3/primitives.json#definitions/financialPositive",
						"title": "Unit Price",
						"description": "A price of one unit of invoice item."
					},
					"amount": {
						"$ref": "https://schemas.pay-cex.io/api/v3/primitives.json#definitions/financialPositive",
						"title": "Amount",
						"description": "Amount of invoice item."
					}
				},
				"required": [
					"description",
					"quantity",
					"unitPrice",
					"amount"
				]
			}
		}
	},
	"required": [
		"currency",
		"amount",
		"notes",
		"items"
	]
}

=== cexiolabs/cexiopay.schemas/api/v3/invoice/invoice.SAMPLE-0.json
{
	"$schema": "https://schemas.pay-cex.io/api/v3/invoice/invoice.json",
	"currency": "USD",
	"amount": "145.45",
	"notes": "Per terms of agreement. Earn Crypto button.",
	"items": [
		{
			"description": "Earn Crypto button 1 : \"Earn Button, April 202X\"",
			"quantity": "4",
			"unitPrice": "25",
			"amount": "100"
		},
		{
			"description": "Earn Crypto button 2 : \"Earn Button, April 202X\"",
			"quantity": "3",
			"unitPrice": "15.15",
			"amount": "45.45"
		}
	]
}
