=== cexiolabs/cexiopay.schemas/processing/v3/account/account.create-request.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "https://schemas.cexpay.io/processing/v3/account/account.create-request.json",
	"title": "Account creation request data transfer object",
	"type": "object",
	"properties": {
		"clientAccountId": {
			"type": [
				"string"
			],
			"maxLength": 128,
			"title": "Client-side account identifier.",
			"description": "It may used to prevent duplicate accounts."
		},
		"clientAccountTag": {
			"type": [
				"string"
			],
			"title": "Optional. Client's data to store along with account.",
			"maxLength": 4096
		},
		"currency": {
			"$ref": "https://schemas.cexpay.io/processing/v3/currency.json#/definitions/currency",
			"title": "Currency code of the account (like 'BTC', 'USD', etc)."
		},
		"triggers": {
			"type": "array",
			"title": "Set of triggers",
			"items": {
				"$ref": "https://schemas.cexpay.io/processing/v3/account/account-trigger.json"
			}
		}
	},
	"required": [
		"clientAccountId",
		"currency"
	]
}

=== cexiolabs/cexiopay.schemas/api/v3/account/account.create-request.SAMPLE-1.json
{
	"$schema": "https://schemas.cexpay.io/api/v3/account/account.create-request.json",
	"clientAccountId": "unique merchant's identifier",
	"clientAccountTag": "Account for merchant's user XXX",
	"currency": "BTC",
	"triggers": [
		{
			"kind": "ORDER_GENERATOR",
			"to": {
				"currency": "USD"
			}
		}
	]
}

=== cexiolabs/cexiopay.schemas/processing/v3/account/account.create-request.SAMPLE-1.json
{
	"$schema": "https://schemas.cexpay.io/processing/v3/account/account.create-request.json",
	"clientAccountId": "unique merchant's identifier",
	"clientAccountTag": "Account for merchant's user XXX",
	"currency": "BTC",
	"triggers": [
		{
			"kind": "ORDER_GENERATOR",
			"to": {
				"currency": "USD"
			}
		}
	]
}
